version: '3.8'
services:
  algbot:
    container_name: algbot
    restart: always
    build: .
    env_file: .env
  visualcube:
    container_name: visualcube
    restart: always
    image: docker.pkg.github.com/nogesma/scrambler/visualcube:latest
    ports:
      - 80:80
